### PR TITLE
Propose gmail url fix

### PR DESCRIPTION
**Pull request by errazudin**
existing works, propose for better visibility

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi @errazudin Thank you for bringing this to my notice. We have a policy to merge PR's only if the merger consist of at least one addition of commands. It would be great if you could just add one more website in the same format as gmail. We will then go ahead with the merge and your name will appear in our contributors tab!
By the way, is this for Hacktoberfest?

**Comment by virejdasani** [comment]
Check this out:
https://github.com/virejdasani/Jarvis/issues/1

**Review by errazudin — COMMENTED** [review]
Hi @virejdasani updated with one additional command for outlook. Yep its for HF

**Comment by virejdasani** [comment]
Merged. Good luck for your HF!

**Comment by errazudin** [comment]
Thanks @virejdasani 👍

**Comment by virejdasani** [comment]
@errazudin If it isn't too much trouble, could you please star this repository, because it helps us reach more contributors. 
Thanks in advance!

**Pull request merged**
